import Head from "next/head"
import { Product } from "@/interfaces/products"
import HomeScreen from "@/screens/HomeScreen"


interface HomeProps {
  products: Product[]
}
export default function Home({products}: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        < HomeScreen products={products} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch("https://fakestoreapi.com/products")
  const products : Product[] = await res.json()
  // By returning { props: { products } }, the Blog component
  // will receive `products` as a prop at build time
  return {
    props: {
      products,
    },
  }
}
